# -*- coding: utf-8 -*-
"""追加31个额外产品，生成JS代码追加到 products-data.js"""
import re, json

more_products = [
  # -- SHIELD 增补 (4个) --
  {
    "sku": "shield-max-cut", "id": "shield-max-cut",
    "name": "PandaSHIELD 终极防切割手套",
    "name_zh": "PandaSHIELD 终极防切割手套",
    "name_en": "PandaSHIELD Max Cut Protection Glove",
    "brand": "shield", "type": "cut",
    "industry": ["metal", "glass", "mining"],
    "sport": [],
    "cert": ["EN388", "ANSI", "CE"],
    "price_sort": 1001, "sales_sort": 1001, "date_sort": "2025-06",
    "badges": ["新品"], "category": "cut",
    "attributes": {"功能点": "终极防切割A9级,超耐磨,高强度", "材料": "不锈钢丝 / HPPE / 芳纶复合", "应用场景": "金属冲压,矿山开采,玻璃处理", "型号": "SHD-MAX-CUT", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "ANSI A9 / EN 388 Level A9", "涂层": "复合涂层加强", "尺码": "7/S - 11/XXL", "颜色": "黑色/黄色", "内衬": "13针HPPE+不锈钢丝+芳纶", "袖口": "安全袖口，可定制", "包装": "6双/袋，60双/箱", "单品尺寸": "10×12×0.6 CM", "单品净重": "0.095 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "7.0 KG", "认证": "CE / ANSI A9 / ISO 9001", "MOQ": "200 双", "交货期": "28天（≥3000双）"},
    "price": {"moq": 200, "sample": "¥258.00", "tiers": [{"qty": "200–999", "price": "¥68.00"}, {"qty": "1,000–2,999", "price": "¥58.00"}, {"qty": "≥3,000", "price": "¥52.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "ANSI A9", "desc": "美国防切割标准A9级", "level": "A9 6000g+ 耐切割力"}, {"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A9 切割"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "终极防护"],
  },
  {
    "sku": "shield-HD-cut", "id": "shield-HD-cut",
    "name": "PandaSHIELD HD 重载防切割手套",
    "name_zh": "PandaSHIELD HD 重载防切割手套",
    "name_en": "PandaSHIELD HD Heavy Cut Protection Glove",
    "brand": "shield", "type": "cut",
    "industry": ["metal", "construction", "mechanical"],
    "sport": [],
    "cert": ["EN388", "ANSI", "CE"],
    "price_sort": 1002, "sales_sort": 1002, "date_sort": "2025-05",
    "badges": [], "category": "cut",
    "attributes": {"功能点": "HD重载防切割,高耐磨,耐撕裂", "材料": "HPPE / 超高分子量聚乙烯 / 丁腈涂层", "应用场景": "金属冲压,重载作业,建筑施工", "型号": "SHD-HD-CUT", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "ANSI A6 / EN 388 Level A6", "涂层": "丁腈加强涂层", "尺码": "7/S - 11/XXL", "颜色": "黑色/灰色", "内衬": "HPPE超高分子量聚乙烯编织", "袖口": "安全袖口，可调节", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.6 CM", "单品净重": "0.080 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "10.0 KG", "认证": "CE / ANSI A6 / ISO 9001", "MOQ": "300 双", "交货期": "25天（≥4000双）"},
    "price": {"moq": 300, "sample": "¥188.00", "tiers": [{"qty": "300–999", "price": "¥48.00"}, {"qty": "1,000–3,999", "price": "¥42.00"}, {"qty": "≥4,000", "price": "¥38.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "ANSI A6", "desc": "美国防切割标准A6级", "level": "A6 2000-2999g 耐切割力"}, {"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A6 切割"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "重载防护"],
  },
  {
    "sku": "shield-precision-HD", "id": "shield-precision-HD",
    "name": "PandaSHIELD 精密HD防护手套",
    "name_zh": "PandaSHIELD 精密HD防护手套",
    "name_en": "PandaSHIELD Precision HD Protection Glove",
    "brand": "shield", "type": "cut",
    "industry": ["electronics", "laboratory", "mechanical"],
    "sport": ["gymnastics"],
    "cert": ["EN388", "CE", "ISO9001"],
    "price_sort": 1003, "sales_sort": 1003, "date_sort": "2025-06",
    "badges": [], "category": "cut",
    "attributes": {"功能点": "精密HD防护,防切割A3,高触感", "材料": "HPPE / 氨纶 / PU薄涂层", "应用场景": "精密仪器,电子装配,实验室操作", "型号": "SHD-PREC-HD", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level A3 切割", "涂层": "PU超薄涂层", "尺码": "6/XS - 9/M", "颜色": "白色/灰色", "内衬": "HPPE+氨纶超薄编织", "袖口": "弹性精密袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "8×10×0.28 CM", "单品净重": "0.022 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "3.5 KG", "认证": "CE / EN 388 Level A3 / ISO 9001", "MOQ": "800 双", "交货期": "15天（≥8000双）"},
    "price": {"moq": 800, "sample": "¥58.00", "tiers": [{"qty": "800–2,999", "price": "¥13.50"}, {"qty": "3,000–7,999", "price": "¥11.80"}, {"qty": "≥8,000", "price": "¥10.50"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A3 切割 / 精密"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "精密", "HD"],
  },
  {
    "sku": "shield-sand-cut", "id": "shield-sand-cut",
    "name": "PandaSHIELD 砂纹切割防护手套",
    "name_zh": "PandaSHIELD 砂纹切割防护手套",
    "name_en": "PandaSHIELD Sand Texture Cut Protection Glove",
    "brand": "shield", "type": "cut",
    "industry": ["automotive", "metal", "construction"],
    "sport": ["bodybuilding"],
    "cert": ["EN388", "CE"],
    "price_sort": 1004, "sales_sort": 1004, "date_sort": "2025-04",
    "badges": [], "category": "cut",
    "attributes": {"功能点": "砂纹防滑涂层,防切割A4,耐磨", "材料": "HPPE / 涤纶 / 砂纹丁腈涂层", "应用场景": "汽车维修,金属加工,建筑施工", "型号": "SHD-SAND", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level A4 / 砂纹防滑", "涂层": "砂纹丁腈掌部防滑涂层", "尺码": "7/S - 11/XXL", "颜色": "蓝色/灰色/黑色", "内衬": "13针HPPE编织", "袖口": "弹性安全袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.5 CM", "单品净重": "0.058 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "7.8 KG", "认证": "CE / EN 388 Level A4 / ISO 9001", "MOQ": "400 双", "交货期": "18天（≥5000双）"},
    "price": {"moq": 400, "sample": "¥78.00", "tiers": [{"qty": "400–1,999", "price": "¥20.00"}, {"qty": "2,000–4,999", "price": "¥18.00"}, {"qty": "≥5,000", "price": "¥16.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A4 切割 / 砂纹防滑"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "砂纹防滑", "耐磨"],
  },
  # -- PIERCE 增补 (2个) --
  {
    "sku": "pierce-saw-heavy", "id": "pierce-saw-heavy",
    "name": "PandaPIERCE 重型锯片防护手套",
    "name_zh": "PandaPIERCE 重型锯片防护手套",
    "name_en": "PandaPIERCE Heavy Duty Saw Blade Protection Glove",
    "brand": "pierce", "type": "puncture",
    "industry": ["woodworking", "metal", "construction"],
    "sport": [],
    "cert": ["EN388", "ANSI", "CE"],
    "price_sort": 1005, "sales_sort": 1005, "date_sort": "2025-05",
    "badges": [], "category": "puncture",
    "attributes": {"功能点": "重型锯片防护,防穿刺,超耐磨", "材料": "复合不锈钢丝 / HPPE / 碳化钨涂层", "应用场景": "重型木工,金属锯切,大型施工", "型号": "PP-SAW-HD", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "ANSI A8 / EN 388 Level A8 + 锯片防护", "涂层": "碳化钨加强涂层", "尺码": "8/M - 11/XXL", "颜色": "黑色/黄色", "内衬": "HPPE+复合不锈钢丝", "袖口": "长筒加强袖口（12cm）", "包装": "6双/袋，60双/箱", "单品尺寸": "12×18×1.0 CM", "单品净重": "0.200 kg", "外箱尺寸": "50×40×30 CM", "外箱毛重": "13.0 KG", "认证": "CE / ANSI A8 / ISO 9001", "MOQ": "100 双", "交货期": "30天（≥2000双）"},
    "price": {"moq": 100, "sample": "¥298.00", "tiers": [{"qty": "100–499", "price": "¥88.00"}, {"qty": "500–1,999", "price": "¥78.00"}, {"qty": "≥2,000", "price": "¥68.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "ANSI A8", "desc": "美国防穿刺A8级标准", "level": "A8 极高穿刺力 4000-4999g"}, {"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A8 切割/穿刺"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "重型锯片防护"],
  },
  {
    "sku": "pierce-light", "id": "pierce-light",
    "name": "PandaPIERCE 轻量防穿刺手套",
    "name_zh": "PandaPIERCE 轻量防穿刺手套",
    "name_en": "PandaPIERCE Lightweight Puncture Resistant Glove",
    "brand": "pierce", "type": "puncture",
    "industry": ["mechanical", "automotive", "electronics"],
    "sport": ["gymnastics"],
    "cert": ["EN388", "CE", "ISO9001"],
    "price_sort": 1006, "sales_sort": 1006, "date_sort": "2025-06",
    "badges": [], "category": "puncture",
    "attributes": {"功能点": "轻量防穿刺,防切割A3,灵活", "材料": "HPPE / 尼龙 / 丁腈涂层", "应用场景": "机械装配,汽车维修,精密作业", "型号": "PP-LIGHT", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level A3 / 穿刺 Level 3", "涂层": "丁腈掌部涂层", "尺码": "6/XS - 11/XXL", "颜色": "蓝色/灰色/白色", "内衬": "HPPE轻量编织", "袖口": "弹性袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.4 CM", "单品净重": "0.040 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "5.5 KG", "认证": "CE / EN 388 Level A3 / ISO 9001", "MOQ": "500 双", "交货期": "15天（≥6000双）"},
    "price": {"moq": 500, "sample": "¥68.00", "tiers": [{"qty": "500–2,499", "price": "¥18.00"}, {"qty": "2,500–4,999", "price": "¥15.80"}, {"qty": "≥5,000", "price": "¥14.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A3 切割 / 穿刺 Level 3"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "轻量", "灵活"],
  },
  # -- IMPACT 增补 (2个) --
  {
    "sku": "impact-XT", "id": "impact-XT",
    "name": "PandaIMPACT XT 极限冲击防护手套",
    "name_zh": "PandaIMPACT XT 极限冲击防护手套",
    "name_en": "PandaIMPACT XT Extreme Impact Protection Glove",
    "brand": "impact", "type": "impact",
    "industry": ["mining", "construction", "metal"],
    "sport": ["weightlifting"],
    "cert": ["EN388", "ANSI", "CE"],
    "price_sort": 1007, "sales_sort": 1007, "date_sort": "2025-06",
    "badges": ["新品"], "category": "impact",
    "attributes": {"功能点": "XT极限冲击防护,ANSI 138 Level 2,超耐磨", "材料": "TPR全掌防护 / HPPE / 耐磨丁腈涂层", "应用场景": "矿山开采,重型锻造,极限施工", "型号": "PI-XT", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "ANSI 138 Level 2 / EN 388 Level A4", "涂层": "耐磨丁腈全掌涂层+TPR", "尺码": "8/M - 11/XXL", "颜色": "黑色/红色", "内衬": "HPPE+TPR全掌防护", "袖口": "TPR护腕+调节扣", "包装": "6双/袋，60双/箱", "单品尺寸": "12×15×1.2 CM", "单品净重": "0.280 kg", "外箱尺寸": "45×35×30 CM", "外箱毛重": "18.0 KG", "认证": "CE / ANSI 138 Level 2 / ISO 9001", "MOQ": "80 双", "交货期": "32天（≥1500双）"},
    "price": {"moq": 80, "sample": "¥128.00", "tiers": [{"qty": "80–299", "price": "¥88.00"}, {"qty": "300–999", "price": "¥78.00"}, {"qty": "≥1,000", "price": "¥68.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "ANSI 138", "desc": "冲击防护手套标准", "level": "Level 2 冲击吸收 / 全掌防护"}, {"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A4 切割"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "极限冲击"],
  },
  {
    "sku": "impact-weld", "id": "impact-weld",
    "name": "PandaIMPACT 焊接冲击防护手套",
    "name_zh": "PandaIMPACT 焊接冲击防护手套",
    "name_en": "PandaIMPACT Welding Impact Protection Glove",
    "brand": "impact", "type": "impact",
    "industry": ["metal", "automotive", "construction"],
    "sport": [],
    "cert": ["EN388", "EN407", "CE"],
    "price_sort": 1008, "sales_sort": 1008, "date_sort": "2025-05",
    "badges": [], "category": "impact",
    "attributes": {"功能点": "焊接+冲击双重防护,阻燃,隔热", "材料": "TPR防护片 / 芳纶 / 牛皮复合", "应用场景": "焊接作业,金属切割,高温车间", "型号": "PI-WELD", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level A4 / EN 407 Level 2 阻燃 / 冲击", "涂层": "牛皮+芳纶复合+TPR冲击片", "尺码": "8/M - 11/XXL", "颜色": "棕黄色/黑色", "内衬": "芳纶隔热层+TPR", "袖口": "长筒焊接袖口（15cm）", "包装": "6双/袋，60双/箱", "单品尺寸": "15×30×1.2 CM", "单品净重": "0.320 kg", "外箱尺寸": "50×40×30 CM", "外箱毛重": "20.0 KG", "认证": "CE / EN 407 Level 2 / ANSI 138 / ISO 9001", "MOQ": "80 双", "交货期": "30天（≥1500双）"},
    "price": {"moq": 80, "sample": "¥118.00", "tiers": [{"qty": "80–299", "price": "¥78.00"}, {"qty": "300–999", "price": "¥68.00"}, {"qty": "≥1,000", "price": "¥60.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 407", "desc": "热/防火防护手套标准", "level": "Level 2 阻燃 / 隔热"}, {"name": "ANSI 138", "desc": "冲击防护手套标准", "level": "冲击保护"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "焊接", "冲击", "阻燃"],
  },
  # -- CHEM 增补 (2个) --
  {
    "sku": "chem-fluoro", "id": "chem-fluoro",
    "name": "PandaCHEM 氟化防护手套",
    "name_zh": "PandaCHEM 氟化防护手套",
    "name_en": "PandaCHEM Fluoroelastomer Chemical Glove",
    "brand": "chem", "type": "chem",
    "industry": ["chemical", "oil", "energy"],
    "sport": [],
    "cert": ["EN374", "CE", "ISO9001"],
    "price_sort": 1009, "sales_sort": 1009, "date_sort": "2025-06",
    "badges": ["新品"], "category": "chem",
    "attributes": {"功能点": "氟化橡胶防护,耐强溶剂,耐高温化学品", "材料": "氟化橡胶(FKM)", "应用场景": "石油化工,航空航天,高纯度化学品", "型号": "PC-FLUORO", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 374-1 Type A / JKL 强溶剂", "涂层": "氟化橡胶(FKM)", "尺码": "7/S - 10/XL", "颜色": "黑色", "内衬": "棉质内衬", "袖口": "加长直筒袖口（38cm）", "包装": "1双/袋，30双/箱", "单品尺寸": "14×40×1.0 CM", "单品净重": "0.450 kg", "外箱尺寸": "55×45×38 CM", "外箱毛重": "14.5 KG", "认证": "CE / EN 374-1 Type A / ISO 9001", "MOQ": "30 双", "交货期": "45天（≥300双）"},
    "price": {"moq": 30, "sample": "¥198.00", "tiers": [{"qty": "30–99", "price": "¥148.00"}, {"qty": "100–299", "price": "¥128.00"}, {"qty": "≥300", "price": "¥118.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 374-1", "desc": "化学品防护手套标准Type A", "level": "J/K/L 强溶剂 / 氟化"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "氟化橡胶"],
  },
  {
    "sku": "chem-silicone", "id": "chem-silicone",
    "name": "PandaCHEM 硅胶防护手套",
    "name_zh": "PandaCHEM 硅胶防护手套",
    "name_en": "PandaCHEM Silicone Chemical Glove",
    "brand": "chem", "type": "chem",
    "industry": ["food", "medical", "laboratory"],
    "sport": [],
    "cert": ["EN374", "CE", "ISO9001"],
    "price_sort": 1010, "sales_sort": 1010, "date_sort": "2025-05",
    "badges": [], "category": "chem",
    "attributes": {"功能点": "食品接触硅胶,耐高温,柔韧", "材料": "食品级硅胶", "应用场景": "食品加工,制药,高温作业", "型号": "PC-SIL", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 374-2 食品接触 / 硅胶安全", "涂层": "食品级硅胶", "尺码": "7/S - 10/XL", "颜色": "透明/红色", "内衬": "无内衬", "袖口": "直筒袖口", "包装": "1双/袋，50双/箱", "单品尺寸": "14×30×0.8 CM", "单品净重": "0.180 kg", "外箱尺寸": "50×40×30 CM", "外箱毛重": "10.0 KG", "认证": "CE / FDA食品接触 / ISO 9001", "MOQ": "100 双", "交货期": "25天（≥1000双）"},
    "price": {"moq": 100, "sample": "¥58.00", "tiers": [{"qty": "100–499", "price": "¥38.00"}, {"qty": "500–999", "price": "¥32.00"}, {"qty": "≥1,000", "price": "¥28.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "FDA", "desc": "美国食品接触材料认证", "level": "食品级硅胶"}, {"name": "EN 374", "desc": "化学品防护手套标准", "level": "EN 374-2 食品接触"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "食品级", "硅胶"],
  },
  # -- BIO 增补 (2个) --
  {
    "sku": "bio-pe", "id": "bio-pe",
    "name": "PandaBIO PE一次性手套",
    "name_zh": "PandaBIO PE一次性手套",
    "name_en": "PandaBIO PE Disposable Glove",
    "brand": "bio", "type": "bio",
    "industry": ["food", "cleaning", "laboratory"],
    "sport": [],
    "cert": ["CE", "ISO9001"],
    "price_sort": 1011, "sales_sort": 1011, "date_sort": "2025-03",
    "badges": [], "category": "bio",
    "attributes": {"功能点": "PE材质,一次性使用,经济实惠", "材料": "聚乙烯(PE)", "应用场景": "食品处理,清洁作业,一般防护", "型号": "PB-PE", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "基础防护标准", "涂层": "聚乙烯(PE)", "尺码": "S/M/L/XL", "颜色": "透明/蓝色", "内衬": "无内衬（一次性）", "袖口": "卷边袖口", "包装": "100只/袋，50袋/箱", "单品尺寸": "22×10×0.02 CM", "单品净重": "0.002 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "5.0 KG", "认证": "CE / ISO 9001", "MOQ": "500 箱", "交货期": "10天（≥1000箱）"},
    "price": {"moq": 500, "sample": "¥12.00", "tiers": [{"qty": "500–2,999", "price": "¥8.00"}, {"qty": "3,000–4,999", "price": "¥7.00"}, {"qty": "≥5,000", "price": "¥6.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "CE 认证", "desc": "欧盟市场准入", "level": "基础防护标准"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "一次性", "经济"],
  },
  {
    "sku": "bio-anti-all", "id": "bio-anti-all",
    "name": "PandaBIO 抗过敏检查手套",
    "name_zh": "PandaBIO 抗过敏检查手套",
    "name_en": "PandaBIO Anti-Allergy Examination Glove",
    "brand": "bio", "type": "bio",
    "industry": ["medical", "laboratory"],
    "sport": [],
    "cert": ["EN374", "EN455", "CE", "ISO9001"],
    "price_sort": 1012, "sales_sort": 1012, "date_sort": "2025-05",
    "badges": ["新品"], "category": "bio",
    "attributes": {"功能点": "抗过敏丁腈,无乳胶无粉,医疗级", "材料": "丁腈(NBR)无乳胶", "应用场景": "医疗检查,护理操作,过敏体质人群", "型号": "PB-ANTIALL", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 455 Class 1 / 抗过敏", "涂层": "丁腈无粉（聚合物涂层）", "尺码": "6/XS - 10/XL", "颜色": "紫色/蓝色/白色", "内衬": "无内衬（一次性）", "袖口": "卷边袖口", "包装": "100只/盒，10盒/箱", "单品尺寸": "20×8×0.05 CM", "单品净重": "0.004 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "5.0 KG", "认证": "CE / EN 455 Class 1 / ISO 9001", "MOQ": "200 箱", "交货期": "15天（≥300箱）"},
    "price": {"moq": 200, "sample": "¥38.00", "tiers": [{"qty": "200–499", "price": "¥26.00"}, {"qty": "500–999", "price": "¥22.00"}, {"qty": "≥1,000", "price": "¥18.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 455", "desc": "医疗检查手套标准", "level": "Class 1 医疗级 / 抗过敏"}, {"name": "EN 374", "desc": "化学品防护手套标准", "level": "微生物防护"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "抗过敏", "医疗级"],
  },
  # -- VOLT 增补 (2个) --
  {
    "sku": "volt-class2", "id": "volt-class2",
    "name": "PandaVOLT Class 2 中压绝缘手套",
    "name_zh": "PandaVOLT Class 2 中压绝缘手套",
    "name_en": "PandaVOLT Class 2 Medium Voltage Insulating Glove",
    "brand": "volt", "type": "insulation",
    "industry": ["energy", "electronics", "construction"],
    "sport": [],
    "cert": ["EN60903", "IEC", "CE"],
    "price_sort": 1013, "sales_sort": 1013, "date_sort": "2025-04",
    "badges": [], "category": "insulation",
    "attributes": {"功能点": "Class 2中压绝缘,AC 17000V,耐用", "材料": "天然乳胶(Class 2)", "应用场景": "中压电力检修,变电站作业,电气设备维护", "型号": "PV-CLASS2", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "IEC 60903 Class 2 / AC 17000V DC 25500V", "涂层": "天然乳胶(Class 2绝缘)", "尺码": "7/S - 11/XXL", "颜色": "红色/黑色", "内衬": "棉质内衬", "袖口": "直筒加长袖口（38cm）", "包装": "1双/袋，20双/箱", "单品尺寸": "10×40×1.5 CM", "单品净重": "0.580 kg", "外箱尺寸": "55×45×38 CM", "外箱毛重": "12.8 KG", "认证": "CE / IEC 60903 Class 2 / ISO 9001", "MOQ": "20 双", "交货期": "35天（≥200双）"},
    "price": {"moq": 20, "sample": "¥188.00", "tiers": [{"qty": "20–99", "price": "¥148.00"}, {"qty": "100–199", "price": "¥128.00"}, {"qty": "≥200", "price": "¥115.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "IEC 60903", "desc": "绝缘手套国际标准", "level": "Class 2 / AC 17000V"}, {"name": "CE 认证", "desc": "欧盟市场准入", "level": "EN 60903 Class 2"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "中压绝缘", "IEC认证"],
  },
  {
    "sku": "volt-arc-pro", "id": "volt-arc-pro",
    "name": "PandaVOLT 电弧专业防护手套",
    "name_zh": "PandaVOLT 电弧专业防护手套",
    "name_en": "PandaVOLT Arc Flash Professional Protection Glove",
    "brand": "volt", "type": "insulation",
    "industry": ["energy", "electronics", "metal"],
    "sport": [],
    "cert": ["EN407", "EN60903", "IEC", "CE"],
    "price_sort": 1014, "sales_sort": 1014, "date_sort": "2025-06",
    "badges": ["新品"], "category": "insulation",
    "attributes": {"功能点": "电弧+绝缘双重防护,ATPV 40cal,Class 0", "材料": "芳纶 / 阻燃棉 / 乳胶(Class 0)", "应用场景": "高压电弧作业,变电站,电力维护", "型号": "PV-ARC-PRO", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "ATPV 40 cal/cm² / IEC 60903 Class 0 / EN 407 Level 4", "涂层": "芳纶+乳胶复合", "尺码": "7/S - 11/XXL", "颜色": "深蓝色/黑色", "内衬": "芳纶阻燃层+棉质", "袖口": "加长防护袖口（38cm）", "包装": "1双/袋，20双/箱", "单品尺寸": "10×40×1.5 CM", "单品净重": "0.480 kg", "外箱尺寸": "55×45×38 CM", "外箱毛重": "10.8 KG", "认证": "CE / ATPV 40cal / IEC 60903 Class 0 / ISO 9001", "MOQ": "30 双", "交货期": "38天（≥400双）"},
    "price": {"moq": 30, "sample": "¥268.00", "tiers": [{"qty": "30–99", "price": "¥198.00"}, {"qty": "100–299", "price": "¥168.00"}, {"qty": "≥300", "price": "¥148.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "ATPV 40cal", "desc": "电弧热防护值", "level": "40 cal/cm²"}, {"name": "IEC 60903", "desc": "绝缘手套国际标准", "level": "Class 0 / AC 1000V"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "电弧防护", "双重防护"],
  },
  # -- HEAT 增补 (2个) --
  {
    "sku": "heat-touch", "id": "heat-touch",
    "name": "PandaHEAT 接触热防护手套",
    "name_zh": "PandaHEAT 接触热防护手套",
    "name_en": "PandaHEAT Contact Heat Protection Glove",
    "brand": "heat", "type": "heat",
    "industry": ["metal", "food", "construction"],
    "sport": [],
    "cert": ["EN407", "CE", "ISO9001"],
    "price_sort": 1015, "sales_sort": 1015, "date_sort": "2025-05",
    "badges": [], "category": "heat",
    "attributes": {"功能点": "接触热防护到500°C,食品接触认证", "材料": "芳纶纤维 / 陶瓷纤维", "应用场景": "金属热处理,食品烘焙,高温作业", "型号": "PH-TOUCH", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 407 Level 4 接触热 500°C", "涂层": "陶瓷纤维隔热层", "尺码": "7/S - 10/XL", "颜色": "银色/灰色", "内衬": "芳纶隔热层", "袖口": "加长防护袖口（20cm）", "包装": "6双/袋，60双/箱", "单品尺寸": "15×25×1.0 CM", "单品净重": "0.160 kg", "外箱尺寸": "45×35×30 CM", "外箱毛重": "10.5 KG", "认证": "CE / EN 407 Level 4 / ISO 9001", "MOQ": "100 双", "交货期": "22天（≥1500双）"},
    "price": {"moq": 100, "sample": "¥78.00", "tiers": [{"qty": "100–499", "price": "¥48.00"}, {"qty": "500–1,499", "price": "¥42.00"}, {"qty": "≥1,500", "price": "¥36.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 407", "desc": "热/防火防护手套标准", "level": "Level 4 接触热 500°C"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "接触热", "耐高温"],
  },
  {
    "sku": "heat-dynamic", "id": "heat-dynamic",
    "name": "PandaHEAT 动态焊接防护手套",
    "name_zh": "PandaHEAT 动态焊接防护手套",
    "name_en": "PandaHEAT Dynamic Welding Protection Glove",
    "brand": "heat", "type": "heat",
    "industry": ["metal", "automotive", "construction"],
    "sport": [],
    "cert": ["EN407", "EN388", "CE"],
    "price_sort": 1016, "sales_sort": 1016, "date_sort": "2025-06",
    "badges": [], "category": "heat",
    "attributes": {"功能点": "动态焊接专用,阻燃,灵活,耐磨", "材料": "芳纶 / 牛皮 / 阻燃涂层", "应用场景": "MIG/MAG焊接,TIG焊接,钎焊作业", "型号": "PH-DYN", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 407 Level 3 阻燃 / EN 388 Level A3", "涂层": "阻燃牛皮+芳纶复合", "尺码": "7/S - 11/XXL", "颜色": "棕黄色/黑色", "内衬": "芳纶隔热层", "袖口": "长筒焊接袖口（18cm）", "包装": "6双/袋，60双/箱", "单品尺寸": "15×32×1.2 CM", "单品净重": "0.260 kg", "外箱尺寸": "50×40×30 CM", "外箱毛重": "17.0 KG", "认证": "CE / EN 407 Level 3 / ISO 9001", "MOQ": "100 双", "交货期": "28天（≥1500双）"},
    "price": {"moq": 100, "sample": "¥98.00", "tiers": [{"qty": "100–499", "price": "¥68.00"}, {"qty": "500–1,499", "price": "¥60.00"}, {"qty": "≥1,500", "price": "¥52.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 407", "desc": "热/防火防护手套标准", "level": "Level 3 阻燃 / 动态焊接"}, {"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A3 切割"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "动态焊接", "灵活"],
  },
  # -- FROST 增补 (2个) --
  {
    "sku": "frost-waterproof", "id": "frost-waterproof",
    "name": "PandaFROST 防水防寒手套",
    "name_zh": "PandaFROST 防水防寒手套",
    "name_en": "PandaFROST Waterproof Cold Protection Glove",
    "brand": "frost", "type": "cold",
    "industry": ["construction", "logistics", "agriculture"],
    "sport": ["skiing", "fishing"],
    "cert": ["EN388", "EN511", "CE"],
    "price_sort": 1017, "sales_sort": 1017, "date_sort": "2025-05",
    "badges": [], "category": "cold",
    "attributes": {"功能点": "防水防寒(-40°C),防风,透气", "材料": "尼龙 / 防水透气膜 / 保暖棉", "应用场景": "冬季施工,冷藏作业,户外运动", "型号": "PF-WATER", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 511 Level 3 / 防水 / -40°C", "涂层": "防水透气膜+保暖棉", "尺码": "7/S - 11/XXL", "颜色": "黑色/深蓝色/橙色", "内衬": "3M Thinsulate保暖层", "袖口": "防风防水袖口（15cm）", "包装": "6双/袋，60双/箱", "单品尺寸": "12×15×1.5 CM", "单品净重": "0.250 kg", "外箱尺寸": "50×40×35 CM", "外箱毛重": "16.5 KG", "认证": "CE / EN 511 Level 3 / ISO 9001", "MOQ": "100 双", "交货期": "28天（≥1500双）"},
    "price": {"moq": 100, "sample": "¥98.00", "tiers": [{"qty": "100–499", "price": "¥58.00"}, {"qty": "500–1,499", "price": "¥50.00"}, {"qty": "≥1,500", "price": "¥45.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 511", "desc": "防寒防护手套标准", "level": "Level 3 / -40°C / 防水"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "防水", "防寒"],
  },
  {
    "sku": "frost-liner", "id": "frost-liner",
    "name": "PandaFROST 保暖内衬手套",
    "name_zh": "PandaFROST 保暖内衬手套",
    "name_en": "PandaFROST Thermal Liner Glove",
    "brand": "frost", "type": "cold",
    "industry": ["construction", "logistics", "metal"],
    "sport": ["hiking", "cycling"],
    "cert": ["EN511", "CE"],
    "price_sort": 1018, "sales_sort": 1018, "date_sort": "2025-04",
    "badges": [], "category": "cold",
    "attributes": {"功能点": "保暖内衬,轻便,透气(-10°C)", "材料": "羊毛 / 涤纶混纺", "应用场景": "秋冬户外作业,一般寒冷环境,室内保暖", "型号": "PF-LINER", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 511 Level 1 / -10°C", "涂层": "透气保暖涂层", "尺码": "7/S - 11/XXL", "颜色": "黑色/灰色/米白色", "内衬": "羊毛涤纶混纺编织", "袖口": "弹性保暖袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.5 CM", "单品净重": "0.060 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "8.0 KG", "认证": "CE / EN 511 Level 1 / ISO 9001", "MOQ": "200 双", "交货期": "15天（≥3000双）"},
    "price": {"moq": 200, "sample": "¥38.00", "tiers": [{"qty": "200–999", "price": "¥18.00"}, {"qty": "1,000–2,999", "price": "¥15.50"}, {"qty": "≥3,000", "price": "¥13.80"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 511", "desc": "防寒防护手套标准", "level": "Level 1 / -10°C / 保暖"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "保暖", "轻便"],
  },
  # -- GRIP 增补 (2个) --
  {
    "sku": "grip-sand", "id": "grip-sand",
    "name": "PandaGRIP 砂纹高防护手套",
    "name_zh": "PandaGRIP 砂纹高防护手套",
    "name_en": "PandaGRIP Sand Texture Heavy Duty Glove",
    "brand": "grip", "type": "grip",
    "industry": ["metal", "construction", "mechanical"],
    "sport": ["weightlifting"],
    "cert": ["EN388", "CE", "ISO9001"],
    "price_sort": 1019, "sales_sort": 1019, "date_sort": "2025-06",
    "badges": [], "category": "grip",
    "attributes": {"功能点": "砂纹防滑,高耐磨,防切割A4", "材料": "HPPE / 涤纶 / 砂纹丁腈涂层", "应用场景": "金属加工,建筑施工,重载搬运", "型号": "PG-SAND", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level A4 / 砂纹防滑", "涂层": "砂纹丁腈加强涂层", "尺码": "7/S - 11/XXL", "颜色": "黑色/灰色", "内衬": "HPPE耐磨编织", "袖口": "弹性安全袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.6 CM", "单品净重": "0.075 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "9.5 KG", "认证": "CE / EN 388 Level A4 / ISO 9001", "MOQ": "300 双", "交货期": "20天（≥4000双）"},
    "price": {"moq": 300, "sample": "¥68.00", "tiers": [{"qty": "300–1,499", "price": "¥18.00"}, {"qty": "1,500–3,999", "price": "¥15.80"}, {"qty": "≥4,000", "price": "¥14.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A4 切割 / 砂纹防滑"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "砂纹", "高防护"],
  },
  {
    "sku": "grip-foam", "id": "grip-foam",
    "name": "PandaGRIP 海绵防滑手套",
    "name_zh": "PandaGRIP 海绵防滑手套",
    "name_en": "PandaGRIP Foam Anti-Slip Glove",
    "brand": "grip", "type": "grip",
    "industry": ["automotive", "mechanical", "construction"],
    "sport": ["bodybuilding"],
    "cert": ["EN388", "CE"],
    "price_sort": 1020, "sales_sort": 1020, "date_sort": "2025-05",
    "badges": [], "category": "grip",
    "attributes": {"功能点": "海绵微孔防滑涂层,透气,防滑", "材料": "尼龙 / 海绵丁腈涂层", "应用场景": "汽车维修,机械装配,一般作业", "型号": "PG-FOAM", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level 3 耐磨 / 海绵防滑", "涂层": "海绵丁腈微孔涂层", "尺码": "7/S - 11/XXL", "颜色": "黑色/蓝色/灰色", "内衬": "尼龙透气编织", "袖口": "弹性袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.5 CM", "单品净重": "0.055 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "7.5 KG", "认证": "CE / EN 388 Level 3 / ISO 9001", "MOQ": "500 双", "交货期": "18天（≥5000双）"},
    "price": {"moq": 500, "sample": "¥42.00", "tiers": [{"qty": "500–2,499", "price": "¥12.50"}, {"qty": "2,500–4,999", "price": "¥11.00"}, {"qty": "≥5,000", "price": "¥9.80"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level 3 耐磨 / 海绵防滑"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "海绵防滑", "透气"],
  },
  # -- ECO 增补 (2个) --
  {
    "sku": "eco-natural", "id": "eco-natural",
    "name": "PandaECO 天然棉防护手套",
    "name_zh": "PandaECO 天然棉防护手套",
    "name_en": "PandaECO Natural Cotton Protection Glove",
    "brand": "eco", "type": "eco",
    "industry": ["food", "agriculture", "construction"],
    "sport": ["gardening"],
    "cert": ["EN388", "CE", "ISO9001"],
    "price_sort": 1021, "sales_sort": 1021, "date_sort": "2025-05",
    "badges": [], "category": "eco",
    "attributes": {"功能点": "天然棉材质,透气,环保", "材料": "100%有机棉 / HPPE", "应用场景": "园林绿化,食品处理,一般防护", "型号": "PE-NAT", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level A2", "涂层": "天然棉编织（无涂层）", "尺码": "7/S - 11/XXL", "颜色": "米白色/浅绿色", "内衬": "100%有机棉编织", "袖口": "弹性环保袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.5 CM", "单品净重": "0.048 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "6.5 KG", "认证": "CE / GOTS有机棉 / ISO 9001", "MOQ": "500 双", "交货期": "18天（≥6000双）"},
    "price": {"moq": 500, "sample": "¥35.00", "tiers": [{"qty": "500–2,499", "price": "¥9.80"}, {"qty": "2,500–5,999", "price": "¥8.50"}, {"qty": "≥6,000", "price": "¥7.50"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "GOTS", "desc": "全球有机纺织品标准", "level": "有机棉认证"}, {"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A2 切割"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "有机棉", "天然"],
  },
  {
    "sku": "eco-HPS", "id": "eco-HPS",
    "name": "PandaECO HPS高性能环保手套",
    "name_zh": "PandaECO HPS高性能环保手套",
    "name_en": "PandaECO HPS High Performance Eco Glove",
    "brand": "eco", "type": "eco",
    "industry": ["metal", "construction", "mechanical"],
    "sport": [],
    "cert": ["EN388", "CE", "ISO9001"],
    "price_sort": 1022, "sales_sort": 1022, "date_sort": "2025-06",
    "badges": ["新品"], "category": "eco",
    "attributes": {"功能点": "HPS高性能,防切割A4,环保材料", "材料": "再生HPPE / 再生尼龙", "应用场景": "绿色施工,机械制造,建筑作业", "型号": "PE-HPS", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level A4", "涂层": "再生丁腈涂层", "尺码": "7/S - 11/XXL", "颜色": "绿色/灰色", "内衬": "再生HPPE编织", "袖口": "弹性环保袖口", "包装": "12双/袋，120双/箱（可回收）", "单品尺寸": "10×12×0.5 CM", "单品净重": "0.052 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "7.0 KG", "认证": "CE / EN 388 Level A4 / ISO 9001", "MOQ": "400 双", "交货期": "20天（≥5000双）"},
    "price": {"moq": 400, "sample": "¥68.00", "tiers": [{"qty": "400–1,999", "price": "¥18.00"}, {"qty": "2,000–4,999", "price": "¥15.80"}, {"qty": "≥5,000", "price": "¥14.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level A4 切割 / 再生材料"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "HPS高性能"],
  },
  # -- NITRILE 增补 (1个) --
  {
    "sku": "nitrile-ultra", "id": "nitrile-ultra",
    "name": "PandaNITRILE 旗舰丁腈手套",
    "name_zh": "PandaNITRILE 旗舰丁腈手套",
    "name_en": "PandaNITRILE Flagship Nitrile Glove",
    "brand": "nitrile", "type": "nitrile",
    "industry": ["chemical", "automotive", "oil"],
    "sport": [],
    "cert": ["EN388", "EN374", "CE", "ISO9001"],
    "price_sort": 1023, "sales_sort": 1023, "date_sort": "2025-06",
    "badges": ["新品"], "category": "nitrile",
    "attributes": {"功能点": "旗舰级丁腈,全面防护,超耐磨", "材料": "尼龙 / 超厚丁腈(NBR)全涂层", "应用场景": "化工重载,石油作业,重型机械", "型号": "PN-ULTRA", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level 4耐磨 / EN 374 Type A", "涂层": "超厚丁腈全掌加强涂层", "尺码": "7/S - 11/XXL", "颜色": "黑色/蓝色/橙色", "内衬": "尼龙耐磨编织", "袖口": "加长安全袖口（10cm）", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.8 CM", "单品净重": "0.110 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "14.0 KG", "认证": "CE / EN 388 Level 4 / EN 374 Type A / ISO 9001", "MOQ": "200 双", "交货期": "25天（≥3000双）"},
    "price": {"moq": 200, "sample": "¥78.00", "tiers": [{"qty": "200–999", "price": "¥22.00"}, {"qty": "1,000–2,999", "price": "¥19.00"}, {"qty": "≥3,000", "price": "¥17.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level 4 耐磨 / 丁腈旗舰"}, {"name": "EN 374-1", "desc": "化学品防护手套标准Type A", "level": "J/K/L 化学品"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "旗舰级"],
  },
  # -- ANTISLIP 增补 (1个) --
  {
    "sku": "antislip-marine", "id": "antislip-marine",
    "name": "PandaANTISLIP 海洋防滑手套",
    "name_zh": "PandaANTISLIP 海洋防滑手套",
    "name_en": "PandaANTISLIP Marine Anti-Slip Glove",
    "brand": "antislip", "type": "grip",
    "industry": ["logistics", "fishing", "construction"],
    "sport": ["fishing", "water-sports"],
    "cert": ["EN388", "CE", "ISO9001"],
    "price_sort": 1024, "sales_sort": 1024, "date_sort": "2025-06",
    "badges": [], "category": "grip",
    "attributes": {"功能点": "海洋/湿滑专用,超强防滑,耐盐水", "材料": "尼龙 / 特殊防滑涂层 / 耐磨橡胶", "应用场景": "海洋作业,渔轮作业,湿滑甲板", "型号": "PA-MARINE", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "EN 388 Level 4 / 超强防滑", "涂层": "特殊耐磨防滑涂层（耐盐水）", "尺码": "7/S - 11/XXL", "颜色": "黑色/黄色", "内衬": "尼龙+防水透气层", "袖口": "防水弹性袖口", "包装": "12双/袋，120双/箱", "单品尺寸": "10×12×0.6 CM", "单品净重": "0.085 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "11.0 KG", "认证": "CE / EN 388 Level 4 / ISO 9001", "MOQ": "300 双", "交货期": "22天（≥3500双）"},
    "price": {"moq": 300, "sample": "¥68.00", "tiers": [{"qty": "300–1,499", "price": "¥18.50"}, {"qty": "1,500–3,499", "price": "¥16.00"}, {"qty": "≥3,500", "price": "¥14.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "EN 388", "desc": "机械风险防护手套标准", "level": "Level 4 耐磨 / 海洋防滑"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "海洋专用", "耐盐水"],
  },
  # -- STATIC 增补 (1个) --
  {
    "sku": "static-ion", "id": "static-ion",
    "name": "PandaSTATIC 离子中和手套",
    "name_zh": "PandaSTATIC 离子中和手套",
    "name_en": "PandaSTATIC Ion Neutralizing Glove",
    "brand": "static", "type": "insulation",
    "industry": ["electronics", "laboratory", "medical"],
    "sport": [],
    "cert": ["EN388", "CE", "ISO9001"],
    "price_sort": 1025, "sales_sort": 1025, "date_sort": "2025-06",
    "badges": ["新品"], "category": "insulation",
    "attributes": {"功能点": "离子中和ESD,高触感,超净", "材料": "银离子导电丝 / 超净尼龙", "应用场景": "先进封装测试,PCB板检测,高精度电子", "型号": "PS-ION", "原产地": "山东，中国", "品牌": "熊猫手护", "防护等级": "表面电阻 10^4-10^6 Ω / EN 388 Level 1", "涂层": "银离子导电丝编织", "尺码": "6/XS - 9/M", "颜色": "白色/银白色", "内衬": "超净尼龙+银离子导电丝", "袖口": "精密弹性袖口（包边）", "包装": "10双/袋，100双/箱（双层密封）", "单品尺寸": "8×10×0.25 CM", "单品净重": "0.016 kg", "外箱尺寸": "40×28×25 CM", "外箱毛重": "2.2 KG", "认证": "CE / 银离子ESD认证 / ISO 9001", "MOQ": "400 双", "交货期": "20天（≥4000双）"},
    "price": {"moq": 400, "sample": "¥52.00", "tiers": [{"qty": "400–1,999", "price": "¥14.50"}, {"qty": "2,000–3,999", "price": "¥12.50"}, {"qty": "≥4,000", "price": "¥11.00"}]},
    "images": ["image/qiege.jpg"],
    "colors": [], "certificates": [{"name": "ESD", "desc": "静电放电防护", "level": "表面电阻 10^4-10^6 Ω / 银离子"}],
    "reviews": {"product": [], "store": []},
    "supplier": {"name": "熊猫手护 Panda Guard", "established": "2010", "responseRate": "95.8%", "responseTime": "<2h", "factoryArea": "15,000 m2", "certifications": ["ISO 9001", "CE", "SGS"]},
    "tags": ["CE认证", "新品", "银离子", "ESD"],
  },
]

print(f"More products count: {len(more_products)}")

# 生成 JS 代码
def to_js_obj(p):
    lines = ["  {"]
    for k, v in p.items():
        indent = "    "
        if isinstance(v, list):
            if not v:
                lines.append(f"{indent}{json.dumps(k)}: [],")
            elif all(isinstance(x, str) for x in v):
                lines.append(f"{indent}{json.dumps(k)}: {json.dumps(v)},")
            else:
                arr_lines = [f"{indent}    {json.dumps(x)}" for x in v]
                lines.append(f"{indent}{json.dumps(k)}: [\n{','.join(arr_lines)}\n{indent}  ],")
        elif isinstance(v, dict):
            kv = ", ".join(f"{json.dumps(key)}: {json.dumps(val)}" for key, val in v.items())
            lines.append(f"{indent}{json.dumps(k)}: {{{kv}}},")
        else:
            lines.append(f"{indent}{json.dumps(k)}: {json.dumps(v)},")
    lines.append("  },")
    return "\n".join(lines)

js_parts = [to_js_obj(p) for p in more_products]
js_code = "\n\n".join(js_parts)
print(js_code)
